name: Daily GARP Screener

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-garp-screener:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Specify the Python version (e.g., 3.9, 3.10, etc.)

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4==4.11.2 openpyxl pandas

    # Run the GARP screener script
    - name: Run GARP Screener
      run: python garp_screener.py

    # Optional: Commit and push the output file (GARP.xlsx) to the repository
    - name: Commit and push output
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add GARP.xlsx
        git commit -m "Update GARP.xlsx with latest data"
        git push
      continue-on-error: true  # Continue even if no changes are made
