name: GARP Screener

on:
  schedule:
    - cron: '30 23 31 12,3,6,9 *'  # Runs at 11:30 PM UTC on the 31st of Dec, Mar, Jun, Sep
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  run-garp-screener:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4==4.11.2 openpyxl pandas html5lib

    # Run the GARP screener script
    - name: Run GARP Screener
      run: python garp_screener.py

    # Commit and push the output files
    - name: Commit and push output
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add GARP.csv GARP_prev.csv GARP_rebalance.csv
        git commit -m "Update GARP files: current, previous, and rebalance" || echo "No changes to commit"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/misterdas/garp.git
      continue-on-error: true
